#!/bin/sh

echo "building 64 bit google-authenticator module"

mkdir -p security/64

cd libpam
./bootstrap.sh
./configure
gmake
mv .libs/pam_google_authenticator.so ../security/64/

gmake clean
CC='/opt/local/gcc47/bin/gcc -m32' ./configure

